// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qmuntal/go3mf/internal/meshinfo (interfaces: Invalidator,MeshInformationContainer,MeshInformation)

// Package meshinfo is a generated GoMock package.
package meshinfo

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInvalidator is a mock of Invalidator interface
type MockInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockInvalidatorMockRecorder
}

// MockInvalidatorMockRecorder is the mock recorder for MockInvalidator
type MockInvalidatorMockRecorder struct {
	mock *MockInvalidator
}

// NewMockInvalidator creates a new mock instance
func NewMockInvalidator(ctrl *gomock.Controller) *MockInvalidator {
	mock := &MockInvalidator{ctrl: ctrl}
	mock.recorder = &MockInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInvalidator) EXPECT() *MockInvalidatorMockRecorder {
	return m.recorder
}

// Invalidate mocks base method
func (m *MockInvalidator) Invalidate(arg0 interface{}) {
	m.ctrl.Call(m, "Invalidate", arg0)
}

// Invalidate indicates an expected call of Invalidate
func (mr *MockInvalidatorMockRecorder) Invalidate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockInvalidator)(nil).Invalidate), arg0)
}

// MockMeshInformationContainer is a mock of MeshInformationContainer interface
type MockMeshInformationContainer struct {
	ctrl     *gomock.Controller
	recorder *MockMeshInformationContainerMockRecorder
}

// MockMeshInformationContainerMockRecorder is the mock recorder for MockMeshInformationContainer
type MockMeshInformationContainerMockRecorder struct {
	mock *MockMeshInformationContainer
}

// NewMockMeshInformationContainer creates a new mock instance
func NewMockMeshInformationContainer(ctrl *gomock.Controller) *MockMeshInformationContainer {
	mock := &MockMeshInformationContainer{ctrl: ctrl}
	mock.recorder = &MockMeshInformationContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMeshInformationContainer) EXPECT() *MockMeshInformationContainerMockRecorder {
	return m.recorder
}

// AddFaceData mocks base method
func (m *MockMeshInformationContainer) AddFaceData(arg0 uint32) (interface{}, error) {
	ret := m.ctrl.Call(m, "AddFaceData", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFaceData indicates an expected call of AddFaceData
func (mr *MockMeshInformationContainerMockRecorder) AddFaceData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFaceData", reflect.TypeOf((*MockMeshInformationContainer)(nil).AddFaceData), arg0)
}

// Clear mocks base method
func (m *MockMeshInformationContainer) Clear() {
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear
func (mr *MockMeshInformationContainerMockRecorder) Clear() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockMeshInformationContainer)(nil).Clear))
}

// GetCurrentFaceCount mocks base method
func (m *MockMeshInformationContainer) GetCurrentFaceCount() uint32 {
	ret := m.ctrl.Call(m, "GetCurrentFaceCount")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetCurrentFaceCount indicates an expected call of GetCurrentFaceCount
func (mr *MockMeshInformationContainerMockRecorder) GetCurrentFaceCount() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentFaceCount", reflect.TypeOf((*MockMeshInformationContainer)(nil).GetCurrentFaceCount))
}

// GetFaceData mocks base method
func (m *MockMeshInformationContainer) GetFaceData(arg0 uint32) (interface{}, error) {
	ret := m.ctrl.Call(m, "GetFaceData", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaceData indicates an expected call of GetFaceData
func (mr *MockMeshInformationContainerMockRecorder) GetFaceData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaceData", reflect.TypeOf((*MockMeshInformationContainer)(nil).GetFaceData), arg0)
}

// clone mocks base method
func (m *MockMeshInformationContainer) clone() MeshInformationContainer {
	ret := m.ctrl.Call(m, "clone")
	ret0, _ := ret[0].(MeshInformationContainer)
	return ret0
}

// clone indicates an expected call of clone
func (mr *MockMeshInformationContainerMockRecorder) clone() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clone", reflect.TypeOf((*MockMeshInformationContainer)(nil).clone))
}

// MockMeshInformation is a mock of MeshInformation interface
type MockMeshInformation struct {
	ctrl     *gomock.Controller
	recorder *MockMeshInformationMockRecorder
}

// MockMeshInformationMockRecorder is the mock recorder for MockMeshInformation
type MockMeshInformationMockRecorder struct {
	mock *MockMeshInformation
}

// NewMockMeshInformation creates a new mock instance
func NewMockMeshInformation(ctrl *gomock.Controller) *MockMeshInformation {
	mock := &MockMeshInformation{ctrl: ctrl}
	mock.recorder = &MockMeshInformationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMeshInformation) EXPECT() *MockMeshInformationMockRecorder {
	return m.recorder
}

// AddFaceData mocks base method
func (m *MockMeshInformation) AddFaceData(arg0 uint32) (interface{}, error) {
	ret := m.ctrl.Call(m, "AddFaceData", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFaceData indicates an expected call of AddFaceData
func (mr *MockMeshInformationMockRecorder) AddFaceData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFaceData", reflect.TypeOf((*MockMeshInformation)(nil).AddFaceData), arg0)
}

// Clear mocks base method
func (m *MockMeshInformation) Clear() {
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear
func (mr *MockMeshInformationMockRecorder) Clear() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockMeshInformation)(nil).Clear))
}

// FaceHasData mocks base method
func (m *MockMeshInformation) FaceHasData(arg0 uint32) bool {
	ret := m.ctrl.Call(m, "FaceHasData", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FaceHasData indicates an expected call of FaceHasData
func (mr *MockMeshInformationMockRecorder) FaceHasData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FaceHasData", reflect.TypeOf((*MockMeshInformation)(nil).FaceHasData), arg0)
}

// GetCurrentFaceCount mocks base method
func (m *MockMeshInformation) GetCurrentFaceCount() uint32 {
	ret := m.ctrl.Call(m, "GetCurrentFaceCount")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetCurrentFaceCount indicates an expected call of GetCurrentFaceCount
func (mr *MockMeshInformationMockRecorder) GetCurrentFaceCount() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentFaceCount", reflect.TypeOf((*MockMeshInformation)(nil).GetCurrentFaceCount))
}

// GetFaceData mocks base method
func (m *MockMeshInformation) GetFaceData(arg0 uint32) (interface{}, error) {
	ret := m.ctrl.Call(m, "GetFaceData", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaceData indicates an expected call of GetFaceData
func (mr *MockMeshInformationMockRecorder) GetFaceData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaceData", reflect.TypeOf((*MockMeshInformation)(nil).GetFaceData), arg0)
}

// GetType mocks base method
func (m *MockMeshInformation) GetType() InformationType {
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(InformationType)
	return ret0
}

// GetType indicates an expected call of GetType
func (mr *MockMeshInformationMockRecorder) GetType() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMeshInformation)(nil).GetType))
}

// Invalidate mocks base method
func (m *MockMeshInformation) Invalidate(arg0 interface{}) {
	m.ctrl.Call(m, "Invalidate", arg0)
}

// Invalidate indicates an expected call of Invalidate
func (mr *MockMeshInformationMockRecorder) Invalidate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockMeshInformation)(nil).Invalidate), arg0)
}

// ResetFaceInformation mocks base method
func (m *MockMeshInformation) ResetFaceInformation(arg0 uint32) {
	m.ctrl.Call(m, "ResetFaceInformation", arg0)
}

// ResetFaceInformation indicates an expected call of ResetFaceInformation
func (mr *MockMeshInformationMockRecorder) ResetFaceInformation(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFaceInformation", reflect.TypeOf((*MockMeshInformation)(nil).ResetFaceInformation), arg0)
}

// clone mocks base method
func (m *MockMeshInformation) clone() MeshInformationContainer {
	ret := m.ctrl.Call(m, "clone")
	ret0, _ := ret[0].(MeshInformationContainer)
	return ret0
}

// clone indicates an expected call of clone
func (mr *MockMeshInformationMockRecorder) clone() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clone", reflect.TypeOf((*MockMeshInformation)(nil).clone))
}

// cloneFaceInfosFrom mocks base method
func (m *MockMeshInformation) cloneFaceInfosFrom(arg0 uint32, arg1 MeshInformation, arg2 uint32) {
	m.ctrl.Call(m, "cloneFaceInfosFrom", arg0, arg1, arg2)
}

// cloneFaceInfosFrom indicates an expected call of cloneFaceInfosFrom
func (mr *MockMeshInformationMockRecorder) cloneFaceInfosFrom(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "cloneFaceInfosFrom", reflect.TypeOf((*MockMeshInformation)(nil).cloneFaceInfosFrom), arg0, arg1, arg2)
}

// getInternalID mocks base method
func (m *MockMeshInformation) getInternalID() uint64 {
	ret := m.ctrl.Call(m, "getInternalID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// getInternalID indicates an expected call of getInternalID
func (mr *MockMeshInformationMockRecorder) getInternalID() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getInternalID", reflect.TypeOf((*MockMeshInformation)(nil).getInternalID))
}

// mergeInformationFrom mocks base method
func (m *MockMeshInformation) mergeInformationFrom(arg0 MeshInformation) {
	m.ctrl.Call(m, "mergeInformationFrom", arg0)
}

// mergeInformationFrom indicates an expected call of mergeInformationFrom
func (mr *MockMeshInformationMockRecorder) mergeInformationFrom(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mergeInformationFrom", reflect.TypeOf((*MockMeshInformation)(nil).mergeInformationFrom), arg0)
}

// permuteNodeInformation mocks base method
func (m *MockMeshInformation) permuteNodeInformation(arg0, arg1, arg2, arg3 uint32) {
	m.ctrl.Call(m, "permuteNodeInformation", arg0, arg1, arg2, arg3)
}

// permuteNodeInformation indicates an expected call of permuteNodeInformation
func (mr *MockMeshInformationMockRecorder) permuteNodeInformation(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "permuteNodeInformation", reflect.TypeOf((*MockMeshInformation)(nil).permuteNodeInformation), arg0, arg1, arg2, arg3)
}

// setInternalID mocks base method
func (m *MockMeshInformation) setInternalID(arg0 uint64) {
	m.ctrl.Call(m, "setInternalID", arg0)
}

// setInternalID indicates an expected call of setInternalID
func (mr *MockMeshInformationMockRecorder) setInternalID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setInternalID", reflect.TypeOf((*MockMeshInformation)(nil).setInternalID), arg0)
}
