package common

// MessageErrorMap defines a mapping between the error code and the message
var MessageErrorMap = map[ErrorCode]string{
	UserAborted:                                   "The called function was aborted by the user",
	ErrorNotImplemented:                           "The called function is not fully implemented",
	ErrorInvalidParam:                             "The call parameter to the function was invalid",
	ErrorCalculationTerminated:                    "The Calculation has to be canceled",
	ErrorCouldNotLoadLibrary:                      "The DLL Library of the DLL Filters could not be loaded",
	ErrorGetProcFailed:                            "The DLL Library of the DLL Filters is invalid",
	ErrorDLLNotLoaded:                             "The DLL Library has not been loaded or could not be loaded",
	ErrorDLLFunctionNotFound:                      "The DLL Library of the DLL Filters is invalid",
	ErrorDLLInvalidParam:                          "The DLL Library has got an invalid parameter",
	ErrorDLLNoInstance:                            "No Instance of the DLL has been created",
	ErrorDLLInvalidFilterName:                     "The DLL does not support the suspected filters",
	ErrorDLLMissingParameter:                      "Not all parameters are provided to the DLL",
	ErrorInvalidBlockSize:                         "The provided Blocksize is invalid (like in CPagedVector)",
	ErrorInvalidIndex:                             "The provided Index is invalid (like in CPagedVector, Node Index)",
	ErrorSingularMatrix:                           "A Matrix could not be inverted in the Matrix functions (as it is singular)",
	ErrorModelMismatch:                            "The Model Object does not match the model which is it added to",
	ErrorAbstract:                                 "The function called is abstract and should not have been called",
	ErrorInvalidHeadBlock:                         "The current block is not assigned",
	ErrorCOMInitializationFailed:                  "COM CoInitialize failed",
	ErrorStandardCPPException:                     "A Standard C++ Exception occurred",
	ErrorInvalidMesh:                              "No mesh has been given",
	ErrorCouldNotCreateContext:                    "Context could not be created",
	ErrorEmptyStringToIntConversion:               "Wanted to convert empty string to integer",
	ErrorInvalidStringToIntConversion:             "Wanted to convert string with non-numeric characters to integer",
	ErrorStringToIntConversionOutOfRange:          "Wanted to convert too large number string to integer",
	ErrorEmptyStringToDoubleConversion:            "Wanted to convert empty string to double",
	ErrorInvalidStringToDoubleConversion:          "Wanted to convert string with non-numeric characters to double",
	ErrorStringToDoubleConversionOutOfRange:       "Wanted to convert too large number string to double",
	ErrorTooManyValuesInMatrixString:              "Too many values (>12) have been found in a matrix string",
	ErrorNotEnoughValuesInMatrixString:            "Not enough values (<12) have been found in a matrix string",
	ErrorInvalidBufferSize:                        "Invalid buffer size",
	ErrorInsufficientBufferSize:                   "Insufficient buffer size",
	ErrorInvalidComponent:                         "No component has been given",
	ErrorInvalidHEXValue:                          "Invalid hex value",
	ErrorRangeError:                               "Range error",
	ErrorInvalidPointer:                           "Passed invalid null pointer",
	ErrorXMLElementNotOpen:                        "XML Element not open",
	ErrorInvalidXMLName:                           "Invalid XML Name",
	ErrorInvalidIntegerTriplet:                    "Invalid Integer Triplet String",
	ErrorInvalidZIPEntryKey:                       "Invalid ZIP Entry key",
	ErrorInvalidZIPName:                           "Invalid ZIP Name",
	ErrorZIPStreamCanNotSeek:                      "ZIP Stream cannot seek",
	ErrorCouldNotConvertToUTF8:                    "Could not convert to UTF8",
	ErrorCouldNotConvertToUTF16:                   "Could not convert to UTF16",
	ErrorZIPEntryOverflow:                         "ZIP Entry overflow",
	ErrorInvalidZIPEntry:                          "Invalid ZIP Entry",
	ErrorExportStreamNotEmpty:                     "Export Stream not empty",
	ErrorDeflateInitFailed:                        "Deflate init failed",
	ErrorZIPAlreadyFinished:                       "Zip already finished",
	ErrorCouldNotDeflate:                          "Could not deflate data",
	ErrorXMLWriterCloseNodeError:                  "Could not close written XML node",
	ErrorInvalidOPCPartURI:                        "Invalid OPC Part URI",
	ErrorCouldNotConvertNumber:                    "Could not convert number",
	ErrorCouldNotGetStreamPosition:                "Could not get stream position",
	ErrorCouldNotReadZIPFile:                      "Could not read ZIP file",
	ErrorCouldNotSeekInZIP:                        "Could not seek in ZIP file",
	ErrorCouldNotStatZIPEntry:                     "Could not stat ZIP entry",
	ErrorCouldNotOpenZIPEntry:                     "Could not open ZIP entry",
	ErrorInvalidXMLDepth:                          "Invalid XML Depth",
	ErrorXMLElementNotEmpty:                       "XML Element not empty",
	ErrorCouldNotInitializeCOM:                    "Could not initialize COM",
	ErrorCallbackStreamCanNotSeek:                 "Callback stream cannot seek",
	ErrorCouldNotWriteToCallbackStream:            "Could not write to callback stream",
	ErrorInvalidCast:                              "Invalid Type Case",
	ErrorBufferIsFull:                             "Buffer is full",
	ErrorCouldNotReadFROMCallbackStream:           "Could not read from callback stream",
	ErrorOPCMissingExtensionForRelationship:       "Content Types does not contain extension for relatioship.",
	ErrorOPCMissingExtensionForModel:              "Content Types does not contain extension or partname for model.",
	ErrorInvalidXMLEncoding:                       "Document is not UTF-8 encoded.",
	ErrorForbiddenXMLAttribute:                    "Document contains a forbidden XML-attribute.",
	ErrorDuplicatePrintTICKET:                     "Document contains more than one printticket.",
	ErrorOPCDuplicateRelationshipID:               "Document contains a duplicate relationship ID.",
	ErrorInvalidRelationshipTypeForTexture:        "A texture must use a OPC part with relationshiptype 3D Texture.",
	ErrorImportStreamIsEmpty:                      "An attachment to be read does not have any content.",
	ErrorUUIDGenerationFailed:                     "Generation of a UUID failed.",
	ErrorZIPEntryNon64TooLarge:                    "A ZIP Entry is too large for non zip64 zip-file",
	ErrorAttachementTooLarge:                      "An individual custom attachment is too large.",
	ErrorZIPCallback:                              "Error in libzip callback.",
	ErrorZIPContainsInconsistencies:               "ZIP file contains inconsistencies. It might load with errors or incorrectly.",
	ErrorGenericException:                         "uncatched exception",
	ErrorNoProgressInterval:                       "No Progress Interval has been specified in the progress handler",
	ErrorDuplicateNode:                            "An Edge with two identical nodes has been tried to added to a mesh",
	ErrorTooManyNodes:                             "The mesh exceeds more than MeshMAXEdgeCount (around two billion) nodes",
	ErrorTooManyFaces:                             "The mesh exceeds more than MeshMAXFaceCount (around two billion) faces",
	ErrorInvalidNodeIndex:                         "The index provided for the node is invalid",
	ErrorInvalidFaceIndex:                         "The index provided for the face is invalid",
	ErrorInvalidMeshTopology:                      "The mesh topology structure is corrupt",
	ErrorInvalidCoordinates:                       "The coordinates exceed MeshMaxCoordinate (= 1 billion mm)",
	ErrorNormalizedZeroVector:                     "A zero Vector has been tried to normalized, which is impossible",
	ErrorCouldNotOpenFile:                         "The specified file could not be opened",
	ErrorCouldNotCreateFile:                       "The specified file could not be created",
	ErrorCouldNotSeekStream:                       "Seeking in a stream was not possible",
	ErrorCouldNotReadStream:                       "Reading from a stream was not possible",
	ErrorCouldNotWriteStream:                      "Writing to a stream was not possible",
	ErrorCouldNotReadFullData:                     "Reading from a stream was only possible partially",
	ErrorCouldNotWriteFullData:                    "Writing to a stream was only possible partially",
	ErrorNoImportStream:                           "No Import Stream was provided to the importer",
	ErrorInvalidFaceCount:                         "The specified facecount in the file was not valid",
	ErrorInvalidUnits:                             "The specified units of the file was not valid",
	ErrorCouldNotSetUnits:                         "The specified units could not be set (for example, the CVectorTree already had some entries)",
	ErrorTooManyEdges:                             "The mesh exceeds more than MeshMAXEdgeCount (around two billion) edges",
	ErrorInvalidEdgeIndex:                         "The index provided for the edge is invalid",
	ErrorDuplicateEdge:                            "The mesh has an face with two identical edges",
	ErrorManifoldEdges:                            "Could not add face to an edge, because it was already two-manifold",
	ErrorCouldNotDeleteEdge:                       "Could not delete edge, because it had attached faces",
	ErrorInternalMergeError:                       "Mesh Merging has failed, because the mesh structure was currupted",
	ErrorEdgesAreNotFormingTriangle:               "The internal triangle structure is corrupted",
	ErrorNoExportStream:                           "No Export Stream was provided to the exporter",
	ErrorCouldNotSetParameter:                     "Could not set parameter, because the queue was not empty",
	ErrorInvalidRECORDSize:                        "Mesh Information records size is invalid",
	ErrorMeshInformationCountMismatch:             "Mesh Information Face Count dies not match with mesh face count",
	ErrorInvalidMeshInformationIndex:              "Could not access mesh information",
	ErrorMeshInformationBufferFull:                "Mesh Information Backup could not be created",
	ErrorNoMeshInformationContainer:               "No Mesh Information Container has been assigned",
	ErrorDiscreteMergeError:                       "Internal Mesh Merge Error because of corrupt mesh structure",
	ErrorDiscreteEdgeLengthViolation:              "Discrete Edges may only have a max length of 30000.",
	ErrorOctreeOutOfBounds:                        "OctTree Node is out of the OctTree Structure",
	ErrorCouldNotDeleteNode:                       "Could not delete mesh node, because it still had some edges connected to it",
	ErrorInvalidInformationType:                   "Mesh Information has not been found",
	ErrorFacesAreNotIdentical:                     "Mesh Information could not be copied",
	ErrorDuplicateTexture:                         "Texture is already existing",
	ErrorDuplicateTextureID:                       "Texture ID is already existing",
	ErrorPartTooLarge:                             "Part is too large",
	ErrorDuplicateTexturePath:                     "Texture path is already existing",
	ErrorDuplicateTextureWidth:                    "Texture width is already existing",
	ErrorDuplicateTextureHeight:                   "Texture height is already existing",
	ErrorDuplicateTextureDepth:                    "Texture depth is already existing",
	ErrorDuplicateTextureContentType:              "Texture content type is already existing",
	ErrorDuplicateTextureU:                        "Texture U coordinate is already existing",
	ErrorDuplicateTextureV:                        "Texture V coordinate is already existing",
	ErrorDuplicateTextureW:                        "Texture W coordinate is already existing",
	ErrorDuplicateTextureSCALE:                    "Texture scale is already existing",
	ErrorDuplicateTextureRotation:                 "Texture rotation is already existing",
	ErrorDuplicateTitlestyleU:                     "Texture tilestyle U is already existing",
	ErrorDuplicateTitlestyleV:                     "Texture tilestyle V is already existing",
	ErrorDuplicateTitlestyleW:                     "Texture tilestyle W is already existing",
	ErrorDuplicateColorID:                         "Color ID is already existing",
	ErrorInvalidMeshInformationData:               "Mesh Information Block was not assigned",
	ErrorInvalidMeshInformation:                   "Mesh Information Object was not assigned",
	ErrorTooManyBeams:                             "The mesh exceeds more than MeshMAXBeamCount (around two billion) beams",
	ErrorOPCReadFailed:                            "3MF Loading - OPC could not be loaded",
	ErrorNoModelStream:                            "No model stream in OPC Container",
	ErrorModelReadFailed:                          "Model XML could not be parsed",
	ErrorNo3MFObject:                              "No 3MF Object in OPC Container",
	ErrorCouldNotWriteModelStream:                 "Could not write Model Stream to OPC Container",
	ErrorOPCFactoryCreateFailed:                   "Could not create OPC Factory",
	ErrorOPCPartSetReadFailed:                     "Could not read OPC Part Set",
	ErrorOPCRelationshipSetReadFailed:             "Could not read OPC Relationship Set",
	ErrorOPCRelationshipSourceURIFailed:           "Could not get Relationship Source URI",
	ErrorOPCRelationshipTargetURIFailed:           "Could not get Relationship Target URI",
	ErrorOPCRelationshipCombineURIFailed:          "Could not Combine Relationship URIs",
	ErrorOPCRelationshipGetPartFailed:             "Could not get Relationship Part",
	ErrorOPCGetContentTypeFailed:                  "Could not retrieve content type",
	ErrorOPCContentTypeMismatch:                   "Content type mismatch",
	ErrorOPCRelationshipEnumerationFailed:         "Could not enumerate relationships",
	ErrorOPCRelationshipNotFound:                  "Could not find relationship type",
	ErrorOPCRelationshipNotUnique:                 "Ambiguous relationship type",
	ErrorOPCCouldNotGetModelStream:                "Could not get OPC Model Stream",
	ErrorCreateXMLReaderFailed:                    "Could not create XML Reader",
	ErrorSetXMLReaderInputFailed:                  "Could not set XML reader input",
	ErrorCouldNotSeekModelStream:                  "Could not seek in XML Model Stream",
	ErrorSetXMLPropertiesFailed:                   "Could not set XML reader properties",
	ErrorReadXMLNodeFailed:                        "Could not read XML node",
	ErrorCouldNotGetLocalXMLName:                  "Could not retrieve local xml node name",
	ErrorCouldParseXMLContent:                     "Could not parse XML Node content",
	ErrorCouldNotGetXMLText:                       "Could not get XML Node value",
	ErrorCouldNotGetXMLAttributes:                 "Could not retrieve XML Node attributes",
	ErrorCouldNotGetXMLValue:                      "Could not get XML attribute value",
	ErrorAlreadyParsedXMLNode:                     "XML Node has already been parsed",
	ErrorInvalidModelUnit:                         "Invalid Model Unit",
	ErrorInvalidModelObjectID:                     "Invalid Model Object ID",
	ErrorMissingModelObjectID:                     "No Model Object ID has been given",
	ErrorDuplicateModelObject:                     "Model Object is already existing",
	ErrorDuplicateObjectID:                        "Model Object ID was given twice",
	ErrorAmbiguousObjectDefinition:                "Model Object Content was ambiguous",
	ErrorModelCoordinateMissing:                   "Model Vertex is missing a coordinate",
	ErrorInvalidModelCoordinates:                  "Invalid Model Coordinates",
	ErrorInvalidModelCoordinateIndices:            "Invalid Model Coordinate Indices",
	ErrorNodeNameIsEmpty:                          "XML Node Name is empty",
	ErrorInvalidModelNodeIndex:                    "Invalid model node index",
	ErrorOPCPackageCreateFailed:                   "Could not create OPC Package",
	ErrorCouldNotWriteOPCPackageToStream:          "Could not write OPC Package to Stream",
	ErrorCouldNotCreateOPCPartURI:                 "Could not create OPC Part URI",
	ErrorCouldNotCreateOPCPart:                    "Could not create OPC Part",
	ErrorOPCCouldNotGetContentStream:              "Could not get OPC Content Stream",
	ErrorOPCCouldNotResizeStream:                  "Could not resize OPC Stream",
	ErrorOPCCouldNotSeekStream:                    "Could not seek in OPC Stream",
	ErrorOPCCouldNotCopyStream:                    "Could not copy OPC Stream",
	ErrorCouldNotRetrieveOPCPartName:              "Could not retrieve OPC Part name",
	ErrorCouldNotCreateOPCRelationship:            "Could not create OPC Relationship",
	ErrorCouldNotCreateXMLWriter:                  "Could not create XML Writer",
	ErrorCouldNotSetXMLOutput:                     "Could not set XML Output stream",
	ErrorCouldNotSetXMLProperty:                   "Could not set XML Property",
	ErrorCouldNotWriteXMLStartDocument:            "Could not write XML Start Document",
	ErrorCouldNotWriteXMLEndDocument:              "Could not write XML End Document",
	ErrorCouldNotFlushXMLWriter:                   "Could not flush XML Writer",
	ErrorCouldNotWriteXMLStartElement:             "Could not write XML Start Element",
	ErrorCouldNotWriteXMLEndElement:               "Could not write XML End Element",
	ErrorCouldNotWriteXMLAttribute:                "Could not write XML Attribute String",
	ErrorMissingBuildItemObjectID:                 "Build item Object ID was not specified",
	ErrorDuplicateBuildItemObjectID:               "Build item Object ID is ambiguous ",
	ErrorInvalidBuildItemObjectID:                 "Build item Object ID is invalid",
	ErrorCouldNotFindBuildItemObject:              "Could not find Object associated to the Build item ",
	ErrorCouldNotFindComponentObject:              "Could not find Object associated to Component",
	ErrorDuplicateComponentObjectID:               "Component Object ID is ambiguous ",
	ErrorMissingModelTextureID:                    "Texture ID was not specified",
	ErrorMissingObjectContent:                     "An object has no supported content type",
	ErrorInvalidReaderObject:                      "Invalid model reader object",
	ErrorInvalidWriterObject:                      "Invalid model writer object",
	ErrorUnknownModelResource:                     "Unknown model resource",
	ErrorInvalidStreamType:                        "Invalid stream type",
	ErrorDuplicateMaterialID:                      "Duplicate Material ID",
	ErrorDuplicateWallThickness:                   "Duplicate Wallthickness",
	ErrorDuplicateFit:                             "Duplicate Fit",
	ErrorDuplicateObjectType:                      "Duplicate Object Type",
	ErrorModelTextureCoordinateMissing:            "Texture coordinates missing",
	ErrorTooManyValuesInColorString:               "Too many values in color string",
	ErrorInvalidValueInColorString:                "Invalid value in color string",
	ErrorDuplicateColorValue:                      "Duplicate node color value",
	ErrorMissingModelColorID:                      "Missing model color ID",
	ErrorMissingModelMaterialID:                   "Missing model material ID",
	ErrorInvalidBuildItem:                         "No Build Item has been given",
	ErrorInvalidObject:                            "No Object has been given",
	ErrorInvalidModel:                             "No Model has been given",
	ErrorInvalidModelResource:                     "No valid Model Resource has been given",
	ErrorDuplicateMetadata:                        "Duplicate Model Metadata",
	ErrorInvalidMetadata:                          "Invalid Model Metadata",
	ErrorInvalidModelComponent:                    "Invalid Model Component",
	ErrorInvalidModelObjectType:                   "Invalid Model Object Type",
	ErrorMissingModelResourceID:                   "Missing Model Resource ID",
	ErrorDuplicateResourceID:                      "Duplicate Resource ID",
	ErrorCouldNotWriteXMLContent:                  "Could not write XML Content",
	ErrorCouldNotGetNamespace:                     "Could not get XML Namespace",
	ErrorHandleOverflow:                           "Handle overflow",
	ErrorNoResources:                              "No resources in model file",
	ErrorNoBuild:                                  "No build section in model file",
	ErrorDuplicateResources:                       "Duplicate resources section in model file",
	ErrorDuplicateBuildSection:                    "Duplicate build section in model file",
	ErrorDuplicateModelNode:                       "Duplicate model node in XML Stream",
	ErrorNoModelNode:                              "No model node in XML Stream",
	ErrorResourceNotFound:                         "Resource not found",
	ErrorUnknownReaderClass:                       "Unknown reader class",
	ErrorUnknownWriterClass:                       "Unknown writer class",
	ErrorModelTextureNotFound:                     "Texture not found",
	ErrorInvalidContentType:                       "Invalid Content Type",
	ErrorInvalidBASEMaterial:                      "Invalid Base Material",
	ErrorTooManyMaterialS:                         "Too many materials",
	ErrorInvalidTexture:                           "Invalid texture",
	ErrorCouldNotGetHandle:                        "Could not get handle",
	ErrorBuildItemNotFound:                        "Build item not found",
	ErrorOPCCouldNotGetTextureURI:                 "Could not get texture URI",
	ErrorOPCCouldNotGetTextureStream:              "Could not get texture stream",
	ErrorModelRelationshipSetReadFailed:           "Model Relationship read failed",
	ErrorNoTexturestream:                          "Texture stream is not available",
	ErrorCouldNotCreateStream:                     "Could not create stream",
	ErrorNotSupportingLegacyCMYK:                  "Not supporting legacy CMYK color",
	ErrorInvalidTextureReference:                  "Invalid Texture Reference",
	ErrorInvalidTextureID:                         "Invalid Texture ID",
	ErrorNoModelToWrite:                           "No model to write",
	ErrorOPCRelationshipGetTypeFailed:             "Failed to get OPC Relationship type",
	ErrorOPCCouldNotGetAttachementURI:             "Could not get attachment URI",
	ErrorDuplicateAttachementPath:                 "Duplicate Attachment Path",
	ErrorInvalidModelAttachement:                  "Invalid Model Attachment",
	ErrorAttachementNotFound:                      "Could not find Model Attachment",
	ErrorInvalidRequiredExtensionPrefix:           "The prefix of a required extension is invalid",
	ErrorRequiredExtensionNotSupported:            "A required extension is not supported",
	ErrorBeamLatticeClippingResourceNotDefined:    "The resource defined as clippingmesh has not yet been defined in the model",
	ErrorBeamLatticeInvalidAttribute:              "An attribute of the beamlattice is invalid",
	ErrorOPCCouldNotGetSlicerefURI:                "Could not get sliceref URI",
	ErrorOPCCouldNotGetSlicerefStream:             "Could not get sliceref stream",
	ErrorOPCCouldNotGetAttachementStream:          "Could not get attachment stream",
	ErrorDuplicateSliceStackID:                    "Object has dublicate slicestack ID",
	ErrorSliceStackResourceNotFound:               "Could not find Slicestack Resource",
	ErrorSliceStackSlicesAndSliceref:              "Slicestack contains slices and slicerefs",
	ErrorIllformatUUID:                            "A UUID is ill formatted",
	ErrorInvalidSliceStack:                        "A slice stack resource is invalid",
	ErrorDuplicatePath:                            "Duplicate path attribute",
	ErrorDuplicateUUID:                            "Duplicate UUID attribute",
	ErrorReferencesTooDeep:                        "References in production extension go deeper than one level.",
	ErrorSlicerefsTooDeep:                         "A slicestack referenced via a slicepath cannot reference another slicestack.",
	ErrorSlicesZNotIncreasing:                     "The z-coordinates of slices within a slicestack are not increasing.",
	ErrorSlicePolygonNotClose:                     "A slice polygon of a model- or solidsupport-object is not closed.",
	ErrorCloseSlicePolygonIsLine:                  "A closed slice polygon is actually a line.",
	ErrorNamespaceInvalidElement:                  "Invalid Element in namespace.",
	ErrorNamespaceInvalidAttribute:                "Invalid Attribute in namespace.",
	ErrorDuplicateZTop:                            "Duplicate Z-top-value in a slice.",
	ErrorMissingTEZTop:                            "Z-top-value is missing in a slice.",
	ErrorSliceInvalidAttribute:                    "Invalid attribute in slice extension",
	ErrorSliceTransformationPlanar:                "A slicestack possesses a nonplanar transformation.",
	ErrorUUIDNotUnique:                            "A UUID is not unique within a package.",
	ErrorMetadataCouldNotGetNamespace:             "Could not get XML Namespace for a metadatum.",
	ErrorInvalidSliceSegmentVertexIndex:           "Invalid index for slice segment or polygon.",
	ErrorMissingUUID:                              "A UUID for a build, build item or object is missing.",
	ErrorInvalidSlicePath:                         "A slicepath is invalid.",
	ErrorUnknownMetadata:                          "Unknown Model Metadata.",
	ErrorDuplicateMeshResolution:                  "Object has duplicate meshresolution attribute.",
	ErrorInvalidMeshResolution:                    "Object has invalid value for meshresolution attribute.",
	ErrorInvalidReaderWarningsObject:              "Invalid model reader warnings object.",
	ErrorOPCCouldNotGetThumbnailStream:            "Could not get OPC thumbnail stream.",
	ErrorDuplicateObjectThumbnail:                 "Duplicate object thumbnail.",
	ErrorDuplicateThumbnail:                       "Duplicate thumbnail.",
	ErrorDuplicatePID:                             "Duplicate Property ID.",
	ErrorDuplicatePIndex:                          "Duplicate Property Index.",
	ErrorMissingDefaultPID:                        "A MeshObject with triangle-properties is missing a default property.",
	ErrorInvalidDefaultPID:                        "A MeshObject with triangle-properties has an invalid default property.",
	ErrorBuildItemObjectMustNotBeOther:            "Build-item must not reference object of type Other.",
	ErrorDefaultPIDOnComponentsObject:             "A components object must not have a default PID.",
	ErrorBeamLatticeNodesTooClose:                 "Nodes used for a beam are closer then the specified minimal length.",
	ErrorBeamLatticeInvalidRepresentationResource: "The resource defined as representationmesh is invalid.",
	ErrorBeamLatticeInvalidObjectType:             "Beamlattice is defined on wrong object type.",
	ErrorSliceOneVertex:                           "Slice only contains one vertex.",
	ErrorSliceOnePoint:                            "Slice contains only one point within a polygon",
	ErrorInvalidTitlestyle:                        "Invalid Tile Style",
	ErrorInvalidFilter:                            "Invalid Filter",
	ErrorXMLParserInvalidAttribValue:              "Invalid XML attribute value",
	ErrorXMLParserInvalidParseResult:              "Invalid XML parse result",
	ErrorXMLParserTooManyUsedChars:                "Too many XML characters used",
	ErrorXMLParserInvalidEndDelimiter:             "Invalid XML end delimiter",
	ErrorXMLParserInvalidNamespacePrefix:          "Invalid XML namespace prefix",
	ErrorXMLParserCouldNotParseEntity:             "Could not parse XML entity",
	ErrorXMLParserEmptyElementName:                "Empty XML element name",
	ErrorXMLParserInvalidCharacterInElementName:   "Invalid characters in XML element name",
	ErrorXMLParserEmptyInstructionName:            "Empty XML instruction name",
	ErrorXMLParserInvalidInstructionName:          "Invalid XML instruction name",
	ErrorXMLParserCouldNotCloseInstruction:        "Could not close XML instruction",
	ErrorXMLParserCouldNotEndElement:              "Could not end XML element",
	ErrorXMLParserEmptyEndElement:                 "Empty XML end element",
	ErrorXMLParserCouldNotCloseElement:            "Could not close XML element",
	ErrorXMLParserInvalidAttributeName:            "Invalid XML attribute name",
	ErrorXMLParserSpaceInAttributeName:            "Space in XML attribute name",
	ErrorXMLParserNoQuotesAroundAttribute:         "No quotes around XML attribute",
	ErrorDuplicateRelationship:                    "A relationship is duplicated.",
	ErrorDuplicateContentType:                     "A content type is duplicated.",
	ErrorContentTypeEmptyExtension:                "A content type does not have a valid extension.",
	ErrorContentTypeEmptyContentType:              "A content type does not have a content type-value.",
	ErrorContentTypeEmptyPartName:                 "An override content type does not have a partname.",
	ErrorXMLParserInvalidEscapeString:             "XML contains an invalid escape character.",
	ErrorDuplicateBoxAttribute:                    "A box attribute is duplicated.",
	ErrorCouldNotGetInterfaceVersion:              "Could not get interface version",
	ErrorInvalidInterfaceVersion:                  "Invalid interface version",
	ErrorInvalidStreamSize:                        "Invalid stream size",
	ErrorInvalidNameLength:                        "Invalid name length",
	ErrorCouldNotCreateModel:                      "Could not create model",
	ErrorInvalidTextureType:                       "Invalid Texture type",
}
