package common

import (
	"reflect"
	"testing"
)

func TestNewError(t *testing.T) {
	type args struct {
		errorCode ErrorCode
	}
	tests := []struct {
		name string
		args args
		want error
	}{
		{"base", args{UserAborted}, &Error{UserAborted}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := NewError(tt.args.errorCode); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("NewError() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestError_GetErrorCode(t *testing.T) {
	tests := []struct {
		name string
		e    Error
		want ErrorCode
	}{
		{"UserAborted", Error{UserAborted}, UserAborted},
		{"ErrorNotImplemented", Error{ErrorNotImplemented}, ErrorNotImplemented},
		{"Success", Error{}, Success},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.e.GetErrorCode(); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Error.GetErrorCode() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestError_Errort(t *testing.T) {
	tests := []struct {
		name string
		e    Error
		want string
	}{
		{"UserAborted", Error{UserAborted}, "The called function was aborted by the user"},
		{"ErrorNotImplemented", Error{ErrorNotImplemented}, "The called function is not fully implemented"},
		{"ErrorInvalidParam", Error{ErrorInvalidParam}, "The call parameter to the function was invalid"},
		{"ErrorCalculationTerminated", Error{ErrorCalculationTerminated}, "The Calculation has to be canceled"},
		{"ErrorCouldNotLoadLibrary", Error{ErrorCouldNotLoadLibrary}, "The DLL Library of the DLL Filters could not be loaded"},
		{"ErrorGetProcFailed", Error{ErrorGetProcFailed}, "The DLL Library of the DLL Filters is invalid"},
		{"ErrorDLLNotLoaded", Error{ErrorDLLNotLoaded}, "The DLL Library has not been loaded or could not be loaded"},
		{"ErrorDLLFunctionNotFound", Error{ErrorDLLFunctionNotFound}, "The DLL Library of the DLL Filters is invalid"},
		{"ErrorDLLInvalidParam", Error{ErrorDLLInvalidParam}, "The DLL Library has got an invalid parameter"},
		{"ErrorDLLNoInstance", Error{ErrorDLLNoInstance}, "No Instance of the DLL has been created"},
		{"ErrorDLLInvalidFilterName", Error{ErrorDLLInvalidFilterName}, "The DLL does not support the suspected filters"},
		{"ErrorDLLMissingParameter", Error{ErrorDLLMissingParameter}, "Not all parameters are provided to the DLL"},
		{"ErrorInvalidBlockSize", Error{ErrorInvalidBlockSize}, "The provided Blocksize is invalid (like in CPagedVector)"},
		{"ErrorInvalidIndex", Error{ErrorInvalidIndex}, "The provided Index is invalid (like in CPagedVector, Node Index)"},
		{"ErrorSingularMatrix", Error{ErrorSingularMatrix}, "A Matrix could not be inverted in the Matrix functions (as it is singular)"},
		{"ErrorModelMismatch", Error{ErrorModelMismatch}, "The Model Object does not match the model which is it added to"},
		{"ErrorAbstract", Error{ErrorAbstract}, "The function called is abstract and should not have been called"},
		{"ErrorInvalidHeadBlock", Error{ErrorInvalidHeadBlock}, "The current block is not assigned"},
		{"ErrorCOMInitializationFailed", Error{ErrorCOMInitializationFailed}, "COM CoInitialize failed"},
		{"ErrorStandardCPPException", Error{ErrorStandardCPPException}, "A Standard C++ Exception occurred"},
		{"ErrorInvalidMesh", Error{ErrorInvalidMesh}, "No mesh has been given"},
		{"ErrorCouldNotCreateContext", Error{ErrorCouldNotCreateContext}, "Context could not be created"},
		{"ErrorEmptyStringToIntConversion", Error{ErrorEmptyStringToIntConversion}, "Wanted to convert empty string to integer"},
		{"ErrorInvalidStringToIntConversion", Error{ErrorInvalidStringToIntConversion}, "Wanted to convert string with non-numeric characters to integer"},
		{"ErrorStringToIntConversionOutOfRange", Error{ErrorStringToIntConversionOutOfRange}, "Wanted to convert too large number string to integer"},
		{"ErrorEmptyStringToDoubleConversion", Error{ErrorEmptyStringToDoubleConversion}, "Wanted to convert empty string to double"},
		{"ErrorInvalidStringToDoubleConversion", Error{ErrorInvalidStringToDoubleConversion}, "Wanted to convert string with non-numeric characters to double"},
		{"ErrorStringToDoubleConversionOutOfRange", Error{ErrorStringToDoubleConversionOutOfRange}, "Wanted to convert too large number string to double"},
		{"ErrorTooManyValuesInMatrixString", Error{ErrorTooManyValuesInMatrixString}, "Too many values (>12) have been found in a matrix string"},
		{"ErrorNotEnoughValuesInMatrixString", Error{ErrorNotEnoughValuesInMatrixString}, "Not enough values (<12) have been found in a matrix string"},
		{"ErrorInvalidBufferSize", Error{ErrorInvalidBufferSize}, "Invalid buffer size"},
		{"ErrorInsufficientBufferSize", Error{ErrorInsufficientBufferSize}, "Insufficient buffer size"},
		{"ErrorInvalidComponent", Error{ErrorInvalidComponent}, "No component has been given"},
		{"ErrorInvalidHEXValue", Error{ErrorInvalidHEXValue}, "Invalid hex value"},
		{"ErrorRangeError", Error{ErrorRangeError}, "Range error"},
		{"ErrorInvalidPointer", Error{ErrorInvalidPointer}, "Passed invalid null pointer"},
		{"ErrorXMLElementNotOpen", Error{ErrorXMLElementNotOpen}, "XML Element not open"},
		{"ErrorInvalidXMLName", Error{ErrorInvalidXMLName}, "Invalid XML Name"},
		{"ErrorInvalidIntegerTriplet", Error{ErrorInvalidIntegerTriplet}, "Invalid Integer Triplet String"},
		{"ErrorInvalidZIPEntryKey", Error{ErrorInvalidZIPEntryKey}, "Invalid ZIP Entry key"},
		{"ErrorInvalidZIPName", Error{ErrorInvalidZIPName}, "Invalid ZIP Name"},
		{"ErrorZIPStreamCanNotSeek", Error{ErrorZIPStreamCanNotSeek}, "ZIP Stream cannot seek"},
		{"ErrorCouldNotConvertToUTF8", Error{ErrorCouldNotConvertToUTF8}, "Could not convert to UTF8"},
		{"ErrorCouldNotConvertToUTF16", Error{ErrorCouldNotConvertToUTF16}, "Could not convert to UTF16"},
		{"ErrorZIPEntryOverflow", Error{ErrorZIPEntryOverflow}, "ZIP Entry overflow"},
		{"ErrorInvalidZIPEntry", Error{ErrorInvalidZIPEntry}, "Invalid ZIP Entry"},
		{"ErrorExportStreamNotEmpty", Error{ErrorExportStreamNotEmpty}, "Export Stream not empty"},
		{"ErrorDeflateInitFailed", Error{ErrorDeflateInitFailed}, "Deflate init failed"},
		{"ErrorZIPAlreadyFinished", Error{ErrorZIPAlreadyFinished}, "Zip already finished"},
		{"ErrorCouldNotDeflate", Error{ErrorCouldNotDeflate}, "Could not deflate data"},
		{"ErrorXMLWriterCloseNodeError", Error{ErrorXMLWriterCloseNodeError}, "Could not close written XML node"},
		{"ErrorInvalidOPCPartURI", Error{ErrorInvalidOPCPartURI}, "Invalid OPC Part URI"},
		{"ErrorCouldNotConvertNumber", Error{ErrorCouldNotConvertNumber}, "Could not convert number"},
		{"ErrorCouldNotGetStreamPosition", Error{ErrorCouldNotGetStreamPosition}, "Could not get stream position"},
		{"ErrorCouldNotReadZIPFile", Error{ErrorCouldNotReadZIPFile}, "Could not read ZIP file"},
		{"ErrorCouldNotSeekInZIP", Error{ErrorCouldNotSeekInZIP}, "Could not seek in ZIP file"},
		{"ErrorCouldNotStatZIPEntry", Error{ErrorCouldNotStatZIPEntry}, "Could not stat ZIP entry"},
		{"ErrorCouldNotOpenZIPEntry", Error{ErrorCouldNotOpenZIPEntry}, "Could not open ZIP entry"},
		{"ErrorInvalidXMLDepth", Error{ErrorInvalidXMLDepth}, "Invalid XML Depth"},
		{"ErrorXMLElementNotEmpty", Error{ErrorXMLElementNotEmpty}, "XML Element not empty"},
		{"ErrorCouldNotInitializeCOM", Error{ErrorCouldNotInitializeCOM}, "Could not initialize COM"},
		{"ErrorCallbackStreamCanNotSeek", Error{ErrorCallbackStreamCanNotSeek}, "Callback stream cannot seek"},
		{"ErrorCouldNotWriteToCallbackStream", Error{ErrorCouldNotWriteToCallbackStream}, "Could not write to callback stream"},
		{"ErrorInvalidCast", Error{ErrorInvalidCast}, "Invalid Type Case"},
		{"ErrorBufferIsFull", Error{ErrorBufferIsFull}, "Buffer is full"},
		{"ErrorCouldNotReadFROMCallbackStream", Error{ErrorCouldNotReadFROMCallbackStream}, "Could not read from callback stream"},
		{"ErrorOPCMissingExtensionForRelationship", Error{ErrorOPCMissingExtensionForRelationship}, "Content Types does not contain extension for relatioship."},
		{"ErrorOPCMissingExtensionForModel", Error{ErrorOPCMissingExtensionForModel}, "Content Types does not contain extension or partname for model."},
		{"ErrorInvalidXMLEncoding", Error{ErrorInvalidXMLEncoding}, "Document is not UTF-8 encoded."},
		{"ErrorForbiddenXMLAttribute", Error{ErrorForbiddenXMLAttribute}, "Document contains a forbidden XML-attribute."},
		{"ErrorDuplicatePrintTICKET", Error{ErrorDuplicatePrintTICKET}, "Document contains more than one printticket."},
		{"ErrorOPCDuplicateRelationshipID", Error{ErrorOPCDuplicateRelationshipID}, "Document contains a duplicate relationship ID."},
		{"ErrorInvalidRelationshipTypeForTexture", Error{ErrorInvalidRelationshipTypeForTexture}, "A texture must use a OPC part with relationshiptype 3D Texture."},
		{"ErrorImportStreamIsEmpty", Error{ErrorImportStreamIsEmpty}, "An attachment to be read does not have any content."},
		{"ErrorUUIDGenerationFailed", Error{ErrorUUIDGenerationFailed}, "Generation of a UUID failed."},
		{"ErrorZIPEntryNon64TooLarge", Error{ErrorZIPEntryNon64TooLarge}, "A ZIP Entry is too large for non zip64 zip-file"},
		{"ErrorAttachementTooLarge", Error{ErrorAttachementTooLarge}, "An individual custom attachment is too large."},
		{"ErrorZIPCallback", Error{ErrorZIPCallback}, "Error in libzip callback."},
		{"ErrorZIPContainsInconsistencies", Error{ErrorZIPContainsInconsistencies}, "ZIP file contains inconsistencies. It might load with errors or incorrectly."},
		{"ErrorGenericException", Error{ErrorGenericException}, "uncatched exception"},
		{"ErrorNoProgressInterval", Error{ErrorNoProgressInterval}, "No Progress Interval has been specified in the progress handler"},
		{"ErrorDuplicateNode", Error{ErrorDuplicateNode}, "An Edge with two identical nodes has been tried to added to a mesh"},
		{"ErrorTooManyNodes", Error{ErrorTooManyNodes}, "The mesh exceeds more than MeshMAXEdgeCount (around two billion) nodes"},
		{"ErrorTooManyFaces", Error{ErrorTooManyFaces}, "The mesh exceeds more than MeshMAXFaceCount (around two billion) faces"},
		{"ErrorInvalidNodeIndex", Error{ErrorInvalidNodeIndex}, "The index provided for the node is invalid"},
		{"ErrorInvalidFaceIndex", Error{ErrorInvalidFaceIndex}, "The index provided for the face is invalid"},
		{"ErrorInvalidMeshTopology", Error{ErrorInvalidMeshTopology}, "The mesh topology structure is corrupt"},
		{"ErrorInvalidCoordinates", Error{ErrorInvalidCoordinates}, "The coordinates exceed MeshMaxCoordinate (= 1 billion mm)"},
		{"ErrorNormalizedZeroVector", Error{ErrorNormalizedZeroVector}, "A zero Vector has been tried to normalized, which is impossible"},
		{"ErrorCouldNotOpenFile", Error{ErrorCouldNotOpenFile}, "The specified file could not be opened"},
		{"ErrorCouldNotCreateFile", Error{ErrorCouldNotCreateFile}, "The specified file could not be created"},
		{"ErrorCouldNotSeekStream", Error{ErrorCouldNotSeekStream}, "Seeking in a stream was not possible"},
		{"ErrorCouldNotReadStream", Error{ErrorCouldNotReadStream}, "Reading from a stream was not possible"},
		{"ErrorCouldNotWriteStream", Error{ErrorCouldNotWriteStream}, "Writing to a stream was not possible"},
		{"ErrorCouldNotReadFullData", Error{ErrorCouldNotReadFullData}, "Reading from a stream was only possible partially"},
		{"ErrorCouldNotWriteFullData", Error{ErrorCouldNotWriteFullData}, "Writing to a stream was only possible partially"},
		{"ErrorNoImportStream", Error{ErrorNoImportStream}, "No Import Stream was provided to the importer"},
		{"ErrorInvalidFaceCount", Error{ErrorInvalidFaceCount}, "The specified facecount in the file was not valid"},
		{"ErrorInvalidUnits", Error{ErrorInvalidUnits}, "The specified units of the file was not valid"},
		{"ErrorCouldNotSetUnits", Error{ErrorCouldNotSetUnits}, "The specified units could not be set (for example, the CVectorTree already had some entries)"},
		{"ErrorTooManyEdges", Error{ErrorTooManyEdges}, "The mesh exceeds more than MeshMAXEdgeCount (around two billion) edges"},
		{"ErrorInvalidEdgeIndex", Error{ErrorInvalidEdgeIndex}, "The index provided for the edge is invalid"},
		{"ErrorDuplicateEdge", Error{ErrorDuplicateEdge}, "The mesh has an face with two identical edges"},
		{"ErrorManifoldEdges", Error{ErrorManifoldEdges}, "Could not add face to an edge, because it was already two-manifold"},
		{"ErrorCouldNotDeleteEdge", Error{ErrorCouldNotDeleteEdge}, "Could not delete edge, because it had attached faces"},
		{"ErrorInternalMergeError", Error{ErrorInternalMergeError}, "Mesh Merging has failed, because the mesh structure was currupted"},
		{"ErrorEdgesAreNotFormingTriangle", Error{ErrorEdgesAreNotFormingTriangle}, "The internal triangle structure is corrupted"},
		{"ErrorNoExportStream", Error{ErrorNoExportStream}, "No Export Stream was provided to the exporter"},
		{"ErrorCouldNotSetParameter", Error{ErrorCouldNotSetParameter}, "Could not set parameter, because the queue was not empty"},
		{"ErrorInvalidRecordSize", Error{ErrorInvalidRecordSize}, "Mesh Information records size is invalid"},
		{"ErrorMeshInformationCountMismatch", Error{ErrorMeshInformationCountMismatch}, "Mesh Information Face Count dies not match with mesh face count"},
		{"ErrorInvalidMeshInformationIndex", Error{ErrorInvalidMeshInformationIndex}, "Could not access mesh information"},
		{"ErrorMeshInformationBufferFull", Error{ErrorMeshInformationBufferFull}, "Mesh Information Backup could not be created"},
		{"ErrorNoMeshInformationContainer", Error{ErrorNoMeshInformationContainer}, "No Mesh Information Container has been assigned"},
		{"ErrorDiscreteMergeError", Error{ErrorDiscreteMergeError}, "Internal Mesh Merge Error because of corrupt mesh structure"},
		{"ErrorDiscreteEdgeLengthViolation", Error{ErrorDiscreteEdgeLengthViolation}, "Discrete Edges may only have a max length of 30000."},
		{"ErrorOctreeOutOfBounds", Error{ErrorOctreeOutOfBounds}, "OctTree Node is out of the OctTree Structure"},
		{"ErrorCouldNotDeleteNode", Error{ErrorCouldNotDeleteNode}, "Could not delete mesh node, because it still had some edges connected to it"},
		{"ErrorInvalidInformationType", Error{ErrorInvalidInformationType}, "Mesh Information has not been found"},
		{"ErrorFacesAreNotIdentical", Error{ErrorFacesAreNotIdentical}, "Mesh Information could not be copied"},
		{"ErrorDuplicateTexture", Error{ErrorDuplicateTexture}, "Texture is already existing"},
		{"ErrorDuplicateTextureID", Error{ErrorDuplicateTextureID}, "Texture ID is already existing"},
		{"ErrorPartTooLarge", Error{ErrorPartTooLarge}, "Part is too large"},
		{"ErrorDuplicateTexturePath", Error{ErrorDuplicateTexturePath}, "Texture path is already existing"},
		{"ErrorDuplicateTextureWidth", Error{ErrorDuplicateTextureWidth}, "Texture width is already existing"},
		{"ErrorDuplicateTextureHeight", Error{ErrorDuplicateTextureHeight}, "Texture height is already existing"},
		{"ErrorDuplicateTextureDepth", Error{ErrorDuplicateTextureDepth}, "Texture depth is already existing"},
		{"ErrorDuplicateTextureContentType", Error{ErrorDuplicateTextureContentType}, "Texture content type is already existing"},
		{"ErrorDuplicateTextureU", Error{ErrorDuplicateTextureU}, "Texture U coordinate is already existing"},
		{"ErrorDuplicateTextureV", Error{ErrorDuplicateTextureV}, "Texture V coordinate is already existing"},
		{"ErrorDuplicateTextureW", Error{ErrorDuplicateTextureW}, "Texture W coordinate is already existing"},
		{"ErrorDuplicateTextureSCALE", Error{ErrorDuplicateTextureSCALE}, "Texture scale is already existing"},
		{"ErrorDuplicateTextureRotation", Error{ErrorDuplicateTextureRotation}, "Texture rotation is already existing"},
		{"ErrorDuplicateTitlestyleU", Error{ErrorDuplicateTitlestyleU}, "Texture tilestyle U is already existing"},
		{"ErrorDuplicateTitlestyleV", Error{ErrorDuplicateTitlestyleV}, "Texture tilestyle V is already existing"},
		{"ErrorDuplicateTitlestyleW", Error{ErrorDuplicateTitlestyleW}, "Texture tilestyle W is already existing"},
		{"ErrorDuplicateColorID", Error{ErrorDuplicateColorID}, "Color ID is already existing"},
		{"ErrorInvalidMeshInformationData", Error{ErrorInvalidMeshInformationData}, "Mesh Information Block was not assigned"},
		{"ErrorInvalidMeshInformation", Error{ErrorInvalidMeshInformation}, "Mesh Information Object was not assigned"},
		{"ErrorTooManyBeams", Error{ErrorTooManyBeams}, "The mesh exceeds more than MeshMAXBeamCount (around two billion) beams"},
		{"ErrorOPCReadFailed", Error{ErrorOPCReadFailed}, "3MF Loading - OPC could not be loaded"},
		{"ErrorNoModelStream", Error{ErrorNoModelStream}, "No model stream in OPC Container"},
		{"ErrorModelReadFailed", Error{ErrorModelReadFailed}, "Model XML could not be parsed"},
		{"ErrorNo3MFObject", Error{ErrorNo3MFObject}, "No 3MF Object in OPC Container"},
		{"ErrorCouldNotWriteModelStream", Error{ErrorCouldNotWriteModelStream}, "Could not write Model Stream to OPC Container"},
		{"ErrorOPCFactoryCreateFailed", Error{ErrorOPCFactoryCreateFailed}, "Could not create OPC Factory"},
		{"ErrorOPCPartSetReadFailed", Error{ErrorOPCPartSetReadFailed}, "Could not read OPC Part Set"},
		{"ErrorOPCRelationshipSetReadFailed", Error{ErrorOPCRelationshipSetReadFailed}, "Could not read OPC Relationship Set"},
		{"ErrorOPCRelationshipSourceURIFailed", Error{ErrorOPCRelationshipSourceURIFailed}, "Could not get Relationship Source URI"},
		{"ErrorOPCRelationshipTargetURIFailed", Error{ErrorOPCRelationshipTargetURIFailed}, "Could not get Relationship Target URI"},
		{"ErrorOPCRelationshipCombineURIFailed", Error{ErrorOPCRelationshipCombineURIFailed}, "Could not Combine Relationship URIs"},
		{"ErrorOPCRelationshipGetPartFailed", Error{ErrorOPCRelationshipGetPartFailed}, "Could not get Relationship Part"},
		{"ErrorOPCGetContentTypeFailed", Error{ErrorOPCGetContentTypeFailed}, "Could not retrieve content type"},
		{"ErrorOPCContentTypeMismatch", Error{ErrorOPCContentTypeMismatch}, "Content type mismatch"},
		{"ErrorOPCRelationshipEnumerationFailed", Error{ErrorOPCRelationshipEnumerationFailed}, "Could not enumerate relationships"},
		{"ErrorOPCRelationshipNotFound", Error{ErrorOPCRelationshipNotFound}, "Could not find relationship type"},
		{"ErrorOPCRelationshipNotUnique", Error{ErrorOPCRelationshipNotUnique}, "Ambiguous relationship type"},
		{"ErrorOPCCouldNotGetModelStream", Error{ErrorOPCCouldNotGetModelStream}, "Could not get OPC Model Stream"},
		{"ErrorCreateXMLReaderFailed", Error{ErrorCreateXMLReaderFailed}, "Could not create XML Reader"},
		{"ErrorSetXMLReaderInputFailed", Error{ErrorSetXMLReaderInputFailed}, "Could not set XML reader input"},
		{"ErrorCouldNotSeekModelStream", Error{ErrorCouldNotSeekModelStream}, "Could not seek in XML Model Stream"},
		{"ErrorSetXMLPropertiesFailed", Error{ErrorSetXMLPropertiesFailed}, "Could not set XML reader properties"},
		{"ErrorReadXMLNodeFailed", Error{ErrorReadXMLNodeFailed}, "Could not read XML node"},
		{"ErrorCouldNotGetLocalXMLName", Error{ErrorCouldNotGetLocalXMLName}, "Could not retrieve local xml node name"},
		{"ErrorCouldParseXMLContent", Error{ErrorCouldParseXMLContent}, "Could not parse XML Node content"},
		{"ErrorCouldNotGetXMLText", Error{ErrorCouldNotGetXMLText}, "Could not get XML Node value"},
		{"ErrorCouldNotGetXMLAttributes", Error{ErrorCouldNotGetXMLAttributes}, "Could not retrieve XML Node attributes"},
		{"ErrorCouldNotGetXMLValue", Error{ErrorCouldNotGetXMLValue}, "Could not get XML attribute value"},
		{"ErrorAlreadyParsedXMLNode", Error{ErrorAlreadyParsedXMLNode}, "XML Node has already been parsed"},
		{"ErrorInvalidModelUnit", Error{ErrorInvalidModelUnit}, "Invalid Model Unit"},
		{"ErrorInvalidModelObjectID", Error{ErrorInvalidModelObjectID}, "Invalid Model Object ID"},
		{"ErrorMissingModelObjectID", Error{ErrorMissingModelObjectID}, "No Model Object ID has been given"},
		{"ErrorDuplicateModelObject", Error{ErrorDuplicateModelObject}, "Model Object is already existing"},
		{"ErrorDuplicateObjectID", Error{ErrorDuplicateObjectID}, "Model Object ID was given twice"},
		{"ErrorAmbiguousObjectDefinition", Error{ErrorAmbiguousObjectDefinition}, "Model Object Content was ambiguous"},
		{"ErrorModelCoordinateMissing", Error{ErrorModelCoordinateMissing}, "Model Vertex is missing a coordinate"},
		{"ErrorInvalidModelCoordinates", Error{ErrorInvalidModelCoordinates}, "Invalid Model Coordinates"},
		{"ErrorInvalidModelCoordinateIndices", Error{ErrorInvalidModelCoordinateIndices}, "Invalid Model Coordinate Indices"},
		{"ErrorNodeNameIsEmpty", Error{ErrorNodeNameIsEmpty}, "XML Node Name is empty"},
		{"ErrorInvalidModelNodeIndex", Error{ErrorInvalidModelNodeIndex}, "Invalid model node index"},
		{"ErrorOPCPackageCreateFailed", Error{ErrorOPCPackageCreateFailed}, "Could not create OPC Package"},
		{"ErrorCouldNotWriteOPCPackageToStream", Error{ErrorCouldNotWriteOPCPackageToStream}, "Could not write OPC Package to Stream"},
		{"ErrorCouldNotCreateOPCPartURI", Error{ErrorCouldNotCreateOPCPartURI}, "Could not create OPC Part URI"},
		{"ErrorCouldNotCreateOPCPart", Error{ErrorCouldNotCreateOPCPart}, "Could not create OPC Part"},
		{"ErrorOPCCouldNotGetContentStream", Error{ErrorOPCCouldNotGetContentStream}, "Could not get OPC Content Stream"},
		{"ErrorOPCCouldNotResizeStream", Error{ErrorOPCCouldNotResizeStream}, "Could not resize OPC Stream"},
		{"ErrorOPCCouldNotSeekStream", Error{ErrorOPCCouldNotSeekStream}, "Could not seek in OPC Stream"},
		{"ErrorOPCCouldNotCopyStream", Error{ErrorOPCCouldNotCopyStream}, "Could not copy OPC Stream"},
		{"ErrorCouldNotRetrieveOPCPartName", Error{ErrorCouldNotRetrieveOPCPartName}, "Could not retrieve OPC Part name"},
		{"ErrorCouldNotCreateOPCRelationship", Error{ErrorCouldNotCreateOPCRelationship}, "Could not create OPC Relationship"},
		{"ErrorCouldNotCreateXMLWriter", Error{ErrorCouldNotCreateXMLWriter}, "Could not create XML Writer"},
		{"ErrorCouldNotSetXMLOutput", Error{ErrorCouldNotSetXMLOutput}, "Could not set XML Output stream"},
		{"ErrorCouldNotSetXMLProperty", Error{ErrorCouldNotSetXMLProperty}, "Could not set XML Property"},
		{"ErrorCouldNotWriteXMLStartDocument", Error{ErrorCouldNotWriteXMLStartDocument}, "Could not write XML Start Document"},
		{"ErrorCouldNotWriteXMLEndDocument", Error{ErrorCouldNotWriteXMLEndDocument}, "Could not write XML End Document"},
		{"ErrorCouldNotFlushXMLWriter", Error{ErrorCouldNotFlushXMLWriter}, "Could not flush XML Writer"},
		{"ErrorCouldNotWriteXMLStartElement", Error{ErrorCouldNotWriteXMLStartElement}, "Could not write XML Start Element"},
		{"ErrorCouldNotWriteXMLEndElement", Error{ErrorCouldNotWriteXMLEndElement}, "Could not write XML End Element"},
		{"ErrorCouldNotWriteXMLAttribute", Error{ErrorCouldNotWriteXMLAttribute}, "Could not write XML Attribute String"},
		{"ErrorMissingBuildItemObjectID", Error{ErrorMissingBuildItemObjectID}, "Build item Object ID was not specified"},
		{"ErrorDuplicateBuildItemObjectID", Error{ErrorDuplicateBuildItemObjectID}, "Build item Object ID is ambiguous "},
		{"ErrorInvalidBuildItemObjectID", Error{ErrorInvalidBuildItemObjectID}, "Build item Object ID is invalid"},
		{"ErrorCouldNotFindBuildItemObject", Error{ErrorCouldNotFindBuildItemObject}, "Could not find Object associated to the Build item "},
		{"ErrorCouldNotFindComponentObject", Error{ErrorCouldNotFindComponentObject}, "Could not find Object associated to Component"},
		{"ErrorDuplicateComponentObjectID", Error{ErrorDuplicateComponentObjectID}, "Component Object ID is ambiguous "},
		{"ErrorMissingModelTextureID", Error{ErrorMissingModelTextureID}, "Texture ID was not specified"},
		{"ErrorMissingObjectContent", Error{ErrorMissingObjectContent}, "An object has no supported content type"},
		{"ErrorInvalidReaderObject", Error{ErrorInvalidReaderObject}, "Invalid model reader object"},
		{"ErrorInvalidWriterObject", Error{ErrorInvalidWriterObject}, "Invalid model writer object"},
		{"ErrorUnknownModelResource", Error{ErrorUnknownModelResource}, "Unknown model resource"},
		{"ErrorInvalidStreamType", Error{ErrorInvalidStreamType}, "Invalid stream type"},
		{"ErrorDuplicateMaterialID", Error{ErrorDuplicateMaterialID}, "Duplicate Material ID"},
		{"ErrorDuplicateWallThickness", Error{ErrorDuplicateWallThickness}, "Duplicate Wallthickness"},
		{"ErrorDuplicateFit", Error{ErrorDuplicateFit}, "Duplicate Fit"},
		{"ErrorDuplicateObjectType", Error{ErrorDuplicateObjectType}, "Duplicate Object Type"},
		{"ErrorModelTextureCoordinateMissing", Error{ErrorModelTextureCoordinateMissing}, "Texture coordinates missing"},
		{"ErrorTooManyValuesInColorString", Error{ErrorTooManyValuesInColorString}, "Too many values in color string"},
		{"ErrorInvalidValueInColorString", Error{ErrorInvalidValueInColorString}, "Invalid value in color string"},
		{"ErrorDuplicateColorValue", Error{ErrorDuplicateColorValue}, "Duplicate node color value"},
		{"ErrorMissingModelColorID", Error{ErrorMissingModelColorID}, "Missing model color ID"},
		{"ErrorMissingModelMaterialID", Error{ErrorMissingModelMaterialID}, "Missing model material ID"},
		{"ErrorInvalidBuildItem", Error{ErrorInvalidBuildItem}, "No Build Item has been given"},
		{"ErrorInvalidObject", Error{ErrorInvalidObject}, "No Object has been given"},
		{"ErrorInvalidModel", Error{ErrorInvalidModel}, "No Model has been given"},
		{"ErrorInvalidModelResource", Error{ErrorInvalidModelResource}, "No valid Model Resource has been given"},
		{"ErrorDuplicateMetadata", Error{ErrorDuplicateMetadata}, "Duplicate Model Metadata"},
		{"ErrorInvalidMetadata", Error{ErrorInvalidMetadata}, "Invalid Model Metadata"},
		{"ErrorInvalidModelComponent", Error{ErrorInvalidModelComponent}, "Invalid Model Component"},
		{"ErrorInvalidModelObjectType", Error{ErrorInvalidModelObjectType}, "Invalid Model Object Type"},
		{"ErrorMissingModelResourceID", Error{ErrorMissingModelResourceID}, "Missing Model Resource ID"},
		{"ErrorDuplicateResourceID", Error{ErrorDuplicateResourceID}, "Duplicate Resource ID"},
		{"ErrorCouldNotWriteXMLContent", Error{ErrorCouldNotWriteXMLContent}, "Could not write XML Content"},
		{"ErrorCouldNotGetNamespace", Error{ErrorCouldNotGetNamespace}, "Could not get XML Namespace"},
		{"ErrorHandleOverflow", Error{ErrorHandleOverflow}, "Handle overflow"},
		{"ErrorNoResources", Error{ErrorNoResources}, "No resources in model file"},
		{"ErrorNoBuild", Error{ErrorNoBuild}, "No build section in model file"},
		{"ErrorDuplicateResources", Error{ErrorDuplicateResources}, "Duplicate resources section in model file"},
		{"ErrorDuplicateBuildSection", Error{ErrorDuplicateBuildSection}, "Duplicate build section in model file"},
		{"ErrorDuplicateModelNode", Error{ErrorDuplicateModelNode}, "Duplicate model node in XML Stream"},
		{"ErrorNoModelNode", Error{ErrorNoModelNode}, "No model node in XML Stream"},
		{"ErrorResourceNotFound", Error{ErrorResourceNotFound}, "Resource not found"},
		{"ErrorUnknownReaderClass", Error{ErrorUnknownReaderClass}, "Unknown reader class"},
		{"ErrorUnknownWriterClass", Error{ErrorUnknownWriterClass}, "Unknown writer class"},
		{"ErrorModelTextureNotFound", Error{ErrorModelTextureNotFound}, "Texture not found"},
		{"ErrorInvalidContentType", Error{ErrorInvalidContentType}, "Invalid Content Type"},
		{"ErrorInvalidBASEMaterial", Error{ErrorInvalidBASEMaterial}, "Invalid Base Material"},
		{"ErrorTooManyMaterialS", Error{ErrorTooManyMaterialS}, "Too many materials"},
		{"ErrorInvalidTexture", Error{ErrorInvalidTexture}, "Invalid texture"},
		{"ErrorCouldNotGetHandle", Error{ErrorCouldNotGetHandle}, "Could not get handle"},
		{"ErrorBuildItemNotFound", Error{ErrorBuildItemNotFound}, "Build item not found"},
		{"ErrorOPCCouldNotGetTextureURI", Error{ErrorOPCCouldNotGetTextureURI}, "Could not get texture URI"},
		{"ErrorOPCCouldNotGetTextureStream", Error{ErrorOPCCouldNotGetTextureStream}, "Could not get texture stream"},
		{"ErrorModelRelationshipSetReadFailed", Error{ErrorModelRelationshipSetReadFailed}, "Model Relationship read failed"},
		{"ErrorNoTexturestream", Error{ErrorNoTexturestream}, "Texture stream is not available"},
		{"ErrorCouldNotCreateStream", Error{ErrorCouldNotCreateStream}, "Could not create stream"},
		{"ErrorNotSupportingLegacyCMYK", Error{ErrorNotSupportingLegacyCMYK}, "Not supporting legacy CMYK color"},
		{"ErrorInvalidTextureReference", Error{ErrorInvalidTextureReference}, "Invalid Texture Reference"},
		{"ErrorInvalidTextureID", Error{ErrorInvalidTextureID}, "Invalid Texture ID"},
		{"ErrorNoModelToWrite", Error{ErrorNoModelToWrite}, "No model to write"},
		{"ErrorOPCRelationshipGetTypeFailed", Error{ErrorOPCRelationshipGetTypeFailed}, "Failed to get OPC Relationship type"},
		{"ErrorOPCCouldNotGetAttachementURI", Error{ErrorOPCCouldNotGetAttachementURI}, "Could not get attachment URI"},
		{"ErrorDuplicateAttachementPath", Error{ErrorDuplicateAttachementPath}, "Duplicate Attachment Path"},
		{"ErrorInvalidModelAttachement", Error{ErrorInvalidModelAttachement}, "Invalid Model Attachment"},
		{"ErrorAttachementNotFound", Error{ErrorAttachementNotFound}, "Could not find Model Attachment"},
		{"ErrorInvalidRequiredExtensionPrefix", Error{ErrorInvalidRequiredExtensionPrefix}, "The prefix of a required extension is invalid"},
		{"ErrorRequiredExtensionNotSupported", Error{ErrorRequiredExtensionNotSupported}, "A required extension is not supported"},
		{"ErrorBeamLatticeClippingResourceNotDefined", Error{ErrorBeamLatticeClippingResourceNotDefined}, "The resource defined as clippingmesh has not yet been defined in the model"},
		{"ErrorBeamLatticeInvalidAttribute", Error{ErrorBeamLatticeInvalidAttribute}, "An attribute of the beamlattice is invalid"},
		{"ErrorOPCCouldNotGetSlicerefURI", Error{ErrorOPCCouldNotGetSlicerefURI}, "Could not get sliceref URI"},
		{"ErrorOPCCouldNotGetSlicerefStream", Error{ErrorOPCCouldNotGetSlicerefStream}, "Could not get sliceref stream"},
		{"ErrorOPCCouldNotGetAttachementStream", Error{ErrorOPCCouldNotGetAttachementStream}, "Could not get attachment stream"},
		{"ErrorDuplicateSliceStackID", Error{ErrorDuplicateSliceStackID}, "Object has dublicate slicestack ID"},
		{"ErrorSliceStackResourceNotFound", Error{ErrorSliceStackResourceNotFound}, "Could not find Slicestack Resource"},
		{"ErrorSliceStackSlicesAndSliceref", Error{ErrorSliceStackSlicesAndSliceref}, "Slicestack contains slices and slicerefs"},
		{"ErrorIllformatUUID", Error{ErrorIllformatUUID}, "A UUID is ill formatted"},
		{"ErrorInvalidSliceStack", Error{ErrorInvalidSliceStack}, "A slice stack resource is invalid"},
		{"ErrorDuplicatePath", Error{ErrorDuplicatePath}, "Duplicate path attribute"},
		{"ErrorDuplicateUUID", Error{ErrorDuplicateUUID}, "Duplicate UUID attribute"},
		{"ErrorReferencesTooDeep", Error{ErrorReferencesTooDeep}, "References in production extension go deeper than one level."},
		{"ErrorSlicerefsTooDeep", Error{ErrorSlicerefsTooDeep}, "A slicestack referenced via a slicepath cannot reference another slicestack."},
		{"ErrorSlicesZNotIncreasing", Error{ErrorSlicesZNotIncreasing}, "The z-coordinates of slices within a slicestack are not increasing."},
		{"ErrorSlicePolygonNotClose", Error{ErrorSlicePolygonNotClose}, "A slice polygon of a model- or solidsupport-object is not closed."},
		{"ErrorCloseSlicePolygonIsLine", Error{ErrorCloseSlicePolygonIsLine}, "A closed slice polygon is actually a line."},
		{"ErrorNamespaceInvalidElement", Error{ErrorNamespaceInvalidElement}, "Invalid Element in namespace."},
		{"ErrorNamespaceInvalidAttribute", Error{ErrorNamespaceInvalidAttribute}, "Invalid Attribute in namespace."},
		{"ErrorDuplicateZTop", Error{ErrorDuplicateZTop}, "Duplicate Z-top-value in a slice."},
		{"ErrorMissingTEZTop", Error{ErrorMissingTEZTop}, "Z-top-value is missing in a slice."},
		{"ErrorSliceInvalidAttribute", Error{ErrorSliceInvalidAttribute}, "Invalid attribute in slice extension"},
		{"ErrorSliceTransformationPlanar", Error{ErrorSliceTransformationPlanar}, "A slicestack possesses a nonplanar transformation."},
		{"ErrorUUIDNotUnique", Error{ErrorUUIDNotUnique}, "A UUID is not unique within a package."},
		{"ErrorMetadataCouldNotGetNamespace", Error{ErrorMetadataCouldNotGetNamespace}, "Could not get XML Namespace for a metadatum."},
		{"ErrorInvalidSliceSegmentVertexIndex", Error{ErrorInvalidSliceSegmentVertexIndex}, "Invalid index for slice segment or polygon."},
		{"ErrorMissingUUID", Error{ErrorMissingUUID}, "A UUID for a build, build item or object is missing."},
		{"ErrorInvalidSlicePath", Error{ErrorInvalidSlicePath}, "A slicepath is invalid."},
		{"ErrorUnknownMetadata", Error{ErrorUnknownMetadata}, "Unknown Model Metadata."},
		{"ErrorDuplicateMeshResolution", Error{ErrorDuplicateMeshResolution}, "Object has duplicate meshresolution attribute."},
		{"ErrorInvalidMeshResolution", Error{ErrorInvalidMeshResolution}, "Object has invalid value for meshresolution attribute."},
		{"ErrorInvalidReaderWarningsObject", Error{ErrorInvalidReaderWarningsObject}, "Invalid model reader warnings object."},
		{"ErrorOPCCouldNotGetThumbnailStream", Error{ErrorOPCCouldNotGetThumbnailStream}, "Could not get OPC thumbnail stream."},
		{"ErrorDuplicateObjectThumbnail", Error{ErrorDuplicateObjectThumbnail}, "Duplicate object thumbnail."},
		{"ErrorDuplicateThumbnail", Error{ErrorDuplicateThumbnail}, "Duplicate thumbnail."},
		{"ErrorDuplicatePID", Error{ErrorDuplicatePID}, "Duplicate Property ID."},
		{"ErrorDuplicatePIndex", Error{ErrorDuplicatePIndex}, "Duplicate Property Index."},
		{"ErrorMissingDefaultPID", Error{ErrorMissingDefaultPID}, "A MeshObject with triangle-properties is missing a default property."},
		{"ErrorInvalidDefaultPID", Error{ErrorInvalidDefaultPID}, "A MeshObject with triangle-properties has an invalid default property."},
		{"ErrorBuildItemObjectMustNotBeOther", Error{ErrorBuildItemObjectMustNotBeOther}, "Build-item must not reference object of type Other."},
		{"ErrorDefaultPIDOnComponentsObject", Error{ErrorDefaultPIDOnComponentsObject}, "A components object must not have a default PID."},
		{"ErrorBeamLatticeNodesTooClose", Error{ErrorBeamLatticeNodesTooClose}, "Nodes used for a beam are closer then the specified minimal length."},
		{"ErrorBeamLatticeInvalidRepresentationResource", Error{ErrorBeamLatticeInvalidRepresentationResource}, "The resource defined as representationmesh is invalid."},
		{"ErrorBeamLatticeInvalidObjectType", Error{ErrorBeamLatticeInvalidObjectType}, "Beamlattice is defined on wrong object type."},
		{"ErrorSliceOneVertex", Error{ErrorSliceOneVertex}, "Slice only contains one vertex."},
		{"ErrorSliceOnePoint", Error{ErrorSliceOnePoint}, "Slice contains only one point within a polygon"},
		{"ErrorInvalidTitlestyle", Error{ErrorInvalidTitlestyle}, "Invalid Tile Style"},
		{"ErrorInvalidFilter", Error{ErrorInvalidFilter}, "Invalid Filter"},
		{"ErrorXMLParserInvalidAttribValue", Error{ErrorXMLParserInvalidAttribValue}, "Invalid XML attribute value"},
		{"ErrorXMLParserInvalidParseResult", Error{ErrorXMLParserInvalidParseResult}, "Invalid XML parse result"},
		{"ErrorXMLParserTooManyUsedChars", Error{ErrorXMLParserTooManyUsedChars}, "Too many XML characters used"},
		{"ErrorXMLParserInvalidEndDelimiter", Error{ErrorXMLParserInvalidEndDelimiter}, "Invalid XML end delimiter"},
		{"ErrorXMLParserInvalidNamespacePrefix", Error{ErrorXMLParserInvalidNamespacePrefix}, "Invalid XML namespace prefix"},
		{"ErrorXMLParserCouldNotParseEntity", Error{ErrorXMLParserCouldNotParseEntity}, "Could not parse XML entity"},
		{"ErrorXMLParserEmptyElementName", Error{ErrorXMLParserEmptyElementName}, "Empty XML element name"},
		{"ErrorXMLParserInvalidCharacterInElementName", Error{ErrorXMLParserInvalidCharacterInElementName}, "Invalid characters in XML element name"},
		{"ErrorXMLParserEmptyInstructionName", Error{ErrorXMLParserEmptyInstructionName}, "Empty XML instruction name"},
		{"ErrorXMLParserInvalidInstructionName", Error{ErrorXMLParserInvalidInstructionName}, "Invalid XML instruction name"},
		{"ErrorXMLParserCouldNotCloseInstruction", Error{ErrorXMLParserCouldNotCloseInstruction}, "Could not close XML instruction"},
		{"ErrorXMLParserCouldNotEndElement", Error{ErrorXMLParserCouldNotEndElement}, "Could not end XML element"},
		{"ErrorXMLParserEmptyEndElement", Error{ErrorXMLParserEmptyEndElement}, "Empty XML end element"},
		{"ErrorXMLParserCouldNotCloseElement", Error{ErrorXMLParserCouldNotCloseElement}, "Could not close XML element"},
		{"ErrorXMLParserInvalidAttributeName", Error{ErrorXMLParserInvalidAttributeName}, "Invalid XML attribute name"},
		{"ErrorXMLParserSpaceInAttributeName", Error{ErrorXMLParserSpaceInAttributeName}, "Space in XML attribute name"},
		{"ErrorXMLParserNoQuotesAroundAttribute", Error{ErrorXMLParserNoQuotesAroundAttribute}, "No quotes around XML attribute"},
		{"ErrorDuplicateRelationship", Error{ErrorDuplicateRelationship}, "A relationship is duplicated."},
		{"ErrorDuplicateContentType", Error{ErrorDuplicateContentType}, "A content type is duplicated."},
		{"ErrorContentTypeEmptyExtension", Error{ErrorContentTypeEmptyExtension}, "A content type does not have a valid extension."},
		{"ErrorContentTypeEmptyContentType", Error{ErrorContentTypeEmptyContentType}, "A content type does not have a content type-value."},
		{"ErrorContentTypeEmptyPartName", Error{ErrorContentTypeEmptyPartName}, "An override content type does not have a partname."},
		{"ErrorXMLParserInvalidEscapeString", Error{ErrorXMLParserInvalidEscapeString}, "XML contains an invalid escape character."},
		{"ErrorDuplicateBoxAttribute", Error{ErrorDuplicateBoxAttribute}, "A box attribute is duplicated."},
		{"ErrorCouldNotGetInterfaceVersion", Error{ErrorCouldNotGetInterfaceVersion}, "Could not get interface version"},
		{"ErrorInvalidInterfaceVersion", Error{ErrorInvalidInterfaceVersion}, "Invalid interface version"},
		{"ErrorInvalidStreamSize", Error{ErrorInvalidStreamSize}, "Invalid stream size"},
		{"ErrorInvalidNameLength", Error{ErrorInvalidNameLength}, "Invalid name length"},
		{"ErrorCouldNotCreateModel", Error{ErrorCouldNotCreateModel}, "Could not create model"},
		{"ErrorInvalidTextureType", Error{ErrorInvalidTextureType}, "Invalid Texture type"},
		{"Unknown", Error{-1}, "unknown error"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.e.Error(); got != tt.want {
				t.Errorf("Exception.Error() = %v, want %v", got, tt.want)
			}
		})
	}
}
