name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Test
      run: go test -race ./...
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.22.0
      id: bump_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_tag.outputs.new_tag }}
        release_name: ${{ steps.bump_tag.outputs.new_tag }}
        draft: true
        prerelease: false